<nav class="navbar navbar-inverse" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<?php echo $this->url(array('controller' => 'dashboard', 'action' => 'show')); ?>">
        <img src="<?php echo $this->baseUrl('/images/magic_logo.png') ?>" alt="Magic the Gathering" style="width:200px; height:60px; margin-top: -2px;">
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <?php
        $options['ulClass'] = 'nav navbar-nav';
        echo $this->navigation()->menu($this->navigation_main)->renderMenu($this->navigation_main, $options); ?>
      <!--<ul class="nav navbar-nav navbar-right">
        <li><a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'logout')); ?>">Odhlásiť</a></li>
      </ul> -->
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
